Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !ImportValue  CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ubuntu-base:14.04
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
  CodeDeployApplication:
    Type: "AWS::CodeDeploy::Application"
  CodeDeployDeploymentGroup:
      Type: "AWS::CodeDeploy::DeploymentGroup"
      Properties:
        ApplicationName: !Ref CodeDeployApplication
        Ec2TagFilters:
          - Key: cfn-example
            Type: KEY_AND_VALUE
            Value: example-app
        ServiceRoleArn: !ImportValue CodeDeployIAMRoleArn
  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Location: !ImportValue AppBuildBucket
        Type: S3
      RoleArn: !ImportValue CodePipelineIAMRoleArn
      Stages:
        - Name: Source
          Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Owner: AWS
              Version: 1
              Provider: CodeCommit
            OutputArtifacts:
            - Name: appsrc
            Configuration:
              BranchName: master
              RepositoryName: !ImportValue CodeCommitRepo
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: appsrc
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: appbuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CodeDeploy
            InputArtifacts:
            - Name: appbuild
            Configuration:
              ApplicationName: !Ref CodeDeployApplication
              DeploymentGroupName: !Ref CodeDeployDeploymentGroup